const data = {
	"Envelope": {
		"Body": {
			"getListaMaquetaAsientosResponse": {
				"return": {
					"mensajes": {
						"mensaje": {
							"_TIPO": "0",
							"_DES_MSG": "La ejecucion ha sido correcta."
						}
					},
					"MAQUETA": {
						"ASIENTO": [
							{
								"_XPOSICION": "8",
								"_YPOSICION": "1",
								"_POSICION": "8",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "9",
								"_DGOBJETO_SITIO": "TV",
								"_GCATEGORIA_ASIENTO": "",
								"_DGCATEGORIA_ASIENTO": "",
								"_NASIENTO": "0",
								"_GESTADO_ASIENTO": "",
								"_DGESTADO_ASIENTO": "",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "3",
								"_YPOSICION": "5",
								"_POSICION": "129",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "8",
								"_DGOBJETO_SITIO": "SSHH",
								"_GCATEGORIA_ASIENTO": "",
								"_DGCATEGORIA_ASIENTO": "",
								"_NASIENTO": "0",
								"_GESTADO_ASIENTO": "",
								"_DGESTADO_ASIENTO": "",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "12",
								"_YPOSICION": "5",
								"_POSICION": "138",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "10",
								"_DGOBJETO_SITIO": "ESCALERA",
								"_GCATEGORIA_ASIENTO": "",
								"_DGCATEGORIA_ASIENTO": "",
								"_NASIENTO": "0",
								"_GESTADO_ASIENTO": "",
								"_DGESTADO_ASIENTO": "",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "9",
								"_YPOSICION": "1",
								"_POSICION": "9",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "8",
								"_DGOBJETO_SITIO": "SSHH",
								"_GCATEGORIA_ASIENTO": "",
								"_DGCATEGORIA_ASIENTO": "",
								"_NASIENTO": "0",
								"_GESTADO_ASIENTO": "",
								"_DGESTADO_ASIENTO": "",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "11",
								"_YPOSICION": "5",
								"_POSICION": "137",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "11",
								"_DGOBJETO_SITIO": "CAFETERIA",
								"_GCATEGORIA_ASIENTO": "",
								"_DGCATEGORIA_ASIENTO": "",
								"_NASIENTO": "0",
								"_GESTADO_ASIENTO": "",
								"_DGESTADO_ASIENTO": "",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "7",
								"_YPOSICION": "1",
								"_POSICION": "7",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "1",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "7",
								"_YPOSICION": "2",
								"_POSICION": "21",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "2",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "7",
								"_YPOSICION": "5",
								"_POSICION": "63",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "3",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "6",
								"_YPOSICION": "1",
								"_POSICION": "6",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "4",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "6",
								"_YPOSICION": "2",
								"_POSICION": "20",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "5",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "6",
								"_YPOSICION": "5",
								"_POSICION": "62",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "6",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "5",
								"_YPOSICION": "1",
								"_POSICION": "5",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "7",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "5",
								"_YPOSICION": "2",
								"_POSICION": "19",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "8",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "5",
								"_YPOSICION": "5",
								"_POSICION": "61",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "9",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "4",
								"_YPOSICION": "1",
								"_POSICION": "4",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "10",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "4",
								"_YPOSICION": "2",
								"_POSICION": "18",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "11",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "4",
								"_YPOSICION": "5",
								"_POSICION": "60",
								"_GNIVEL_PISO": "15",
								"_DGNIVEL_PISO": "PRIMER PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "12",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "13",
								"_YPOSICION": "1",
								"_POSICION": "83",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "13",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "13",
								"_YPOSICION": "2",
								"_POSICION": "97",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "14",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "13",
								"_YPOSICION": "5",
								"_POSICION": "139",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "15",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "12",
								"_YPOSICION": "1",
								"_POSICION": "82",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "16",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "12",
								"_YPOSICION": "2",
								"_POSICION": "96",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "17",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "11",
								"_YPOSICION": "1",
								"_POSICION": "81",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "18",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "11",
								"_YPOSICION": "2",
								"_POSICION": "95",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "19",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "10",
								"_YPOSICION": "1",
								"_POSICION": "80",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "20",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "10",
								"_YPOSICION": "2",
								"_POSICION": "94",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "21",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "10",
								"_YPOSICION": "5",
								"_POSICION": "136",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "22",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "9",
								"_YPOSICION": "1",
								"_POSICION": "79",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "23",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "9",
								"_YPOSICION": "2",
								"_POSICION": "93",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "24",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "9",
								"_YPOSICION": "5",
								"_POSICION": "135",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "25",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "8",
								"_YPOSICION": "1",
								"_POSICION": "78",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "26",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "8",
								"_YPOSICION": "2",
								"_POSICION": "92",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "27",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "8",
								"_YPOSICION": "5",
								"_POSICION": "134",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "28",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "7",
								"_YPOSICION": "1",
								"_POSICION": "77",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "29",
								"_GESTADO_ASIENTO": "82",
								"_DGESTADO_ASIENTO": "VENDIDO",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "7",
								"_YPOSICION": "2",
								"_POSICION": "91",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "30",
								"_GESTADO_ASIENTO": "82",
								"_DGESTADO_ASIENTO": "VENDIDO",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "7",
								"_YPOSICION": "5",
								"_POSICION": "133",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "31",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "6",
								"_YPOSICION": "1",
								"_POSICION": "76",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "32",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "6",
								"_YPOSICION": "2",
								"_POSICION": "90",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "33",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "6",
								"_YPOSICION": "5",
								"_POSICION": "132",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "34",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "5",
								"_YPOSICION": "1",
								"_POSICION": "75",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "35",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "5",
								"_YPOSICION": "2",
								"_POSICION": "89",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "36",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "5",
								"_YPOSICION": "5",
								"_POSICION": "131",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "37",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": "1"
							},
							{
								"_XPOSICION": "4",
								"_YPOSICION": "1",
								"_POSICION": "74",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "38",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "4",
								"_YPOSICION": "2",
								"_POSICION": "88",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "39",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "3",
								"_YPOSICION": "1",
								"_POSICION": "73",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "40",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							},
							{
								"_XPOSICION": "3",
								"_YPOSICION": "2",
								"_POSICION": "87",
								"_GNIVEL_PISO": "16",
								"_DGNIVEL_PISO": "SEGUNDO PISO",
								"_GOBJETO_SITIO": "6",
								"_DGOBJETO_SITIO": "ASIENTO 160°",
								"_GCATEGORIA_ASIENTO": "13",
								"_DGCATEGORIA_ASIENTO": "160°",
								"_NASIENTO": "41",
								"_GESTADO_ASIENTO": "83",
								"_DGESTADO_ASIENTO": "DISPONIBLE",
								"_IESCALA": "0",
								"_IPROMOCION_ASIENTO": "0",
								"_CVARIACION": "",
								"_DVARIACION": "",
								"_IASIENTO_INDIVIDUAL": ""
							}
						]
					}
				},
				"_xmlns:ns2": "http://ws.oltursa.com.pe/",
				"__prefix": "ns2"
			},
			"__prefix": "soap"
		},
		"_xmlns:soap": "http://schemas.xmlsoap.org/soap/envelope/",
		"__prefix": "soap"
	}
}

export function Oltursa() {
	const asientos = data.Envelope.Body.getListaMaquetaAsientosResponse.return.MAQUETA.ASIENTO;

	// Agrupar por piso
	const pisos = {} as Record<string, any[]>;
	let maxX: Record<string, number> = {};
	let maxY: Record<string, number> = {};
	asientos.forEach(a => {
		const piso = a._DGNIVEL_PISO;
		if (!pisos[piso]) pisos[piso] = [];
		pisos[piso].push(a);
		const x = parseInt(a._XPOSICION, 10);
		const y = parseInt(a._YPOSICION, 10);
		maxX[piso] = Math.max(maxX[piso] || 0, x);
		maxY[piso] = Math.max(maxY[piso] || 0, y);
	});

	const renderAsiento = (a: any) => {
		if (a._DGOBJETO_SITIO === 'SSHH') return <span style={{background:'#1976d2',color:'#fff',padding:'2px 6px',borderRadius:4,display:'inline-block'}}>{a._DGOBJETO_SITIO}</span>;
		if (a._DGOBJETO_SITIO === 'TV') return <span style={{background:'#222',color:'#fff',padding:'2px 6px',borderRadius:4,display:'inline-block'}}>{a._DGOBJETO_SITIO}</span>;
		if (a._DGOBJETO_SITIO === 'CAFETERIA') return <span style={{background:'#8d5524',color:'#fff',padding:'2px 6px',borderRadius:4,display:'inline-block'}}>{a._DGOBJETO_SITIO}</span>;
		if (a._DGOBJETO_SITIO === 'ESCALERA') return <span style={{background:'#388e3c',color:'#fff',padding:'2px 6px',borderRadius:4,display:'inline-block'}}>{a._DGOBJETO_SITIO}</span>;
		if (a._DGOBJETO_SITIO) return <span style={{background:'#444',color:'#fff',padding:'2px 6px',borderRadius:4,display:'inline-block'}}>{a._DGOBJETO_SITIO.toLowerCase().replace("asiento","")}</span>;
		if (a._GCATEGORIA_ASIENTO) {
			// Asiento
			const vendido = a._DGESTADO_ASIENTO === 'VENDIDO';
			return (
				<span style={{
					background: vendido ? '#e53935' : '#43a047',
					color: '#fff',
					padding: '2px 6px',
					borderRadius: 4,
					display: 'inline-block',
					minWidth: 24,
					textAlign: 'center',
					opacity: vendido ? 0.6 : 1,
					border: vendido ? '2px solid #b71c1c' : '2px solid #1b5e20',
				}}>
					{a._NASIENTO}
				</span>
			);
		}
		return null;
	};

	return (
		<div>
			<h2>Layout de bus Oltursa</h2>
			<div style={{ display: 'flex', gap: 32 }}>
				{Object.entries(pisos).map(([piso, asientosPiso]) => (
					<div key={piso}>
						<h3>{piso}</h3>
						<div style={{
							display: 'grid',
							gridTemplateColumns: `repeat(${maxX[piso]}, 40px)`,
							gridTemplateRows: `repeat(${maxY[piso]}, 40px)`,
							gap: 6,
							background: '#222',
							padding: 12,
							borderRadius: 8,
							boxShadow: '0 2px 8px #0002',
						}}>
							{Array.from({ length: maxY[piso] }).map((_, yIdx) =>
								Array.from({ length: maxX[piso] }).map((_, xIdx) => {
									const asiento = asientosPiso.find(a => parseInt(a._XPOSICION, 10) === xIdx + 1 && parseInt(a._YPOSICION, 10) === yIdx + 1);
									return (
										<div key={xIdx + '-' + yIdx} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 32 }}>
											{asiento ? renderAsiento(asiento) : null}
										</div>
									);
								})
							)}
						</div>
					</div>
				))}
			</div>
			<div style={{marginTop:16}}>
				<span style={{background:'#43a047',color:'#fff',padding:'2px 6px',borderRadius:4,marginRight:8}}>Libre</span>
				<span style={{background:'#e53935',color:'#fff',padding:'2px 6px',borderRadius:4,marginRight:8}}>Vendido</span>
				<span style={{background:'#1976d2',color:'#fff',padding:'2px 6px',borderRadius:4,marginRight:8}}>SSHH: Baño</span>
				<span style={{background:'#222',color:'#fff',padding:'2px 6px',borderRadius:4,marginRight:8}}>TV: TV</span>
				<span style={{background:'#8d5524',color:'#fff',padding:'2px 6px',borderRadius:4,marginRight:8}}>CAFETERIA: Cafetería</span>
				<span style={{background:'#388e3c',color:'#fff',padding:'2px 6px',borderRadius:4,marginRight:8}}>ESCALERA: Escalera</span>
			</div>
		</div>
	);
}